# Generated by Django 2.0.4 on 2018-04-09 21:43

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
